name: CI

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci --force
        
      - name: Build
        run: npm run build
        
      - name: Test
        run: npm run test
        
      - name: Remove tests folder
        run: rm -rf build/tests
      
      - name: Deploy
        uses: s0/git-publish-subdir-action@v2.5.1
        env:
          REPO: self
          BRANCH: package
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Deploy {sha}:\n{msg}"
